### ISSUE TITLE
upstream "invoiceplane" not found

### ISSUE THREAD

**Issue by beli3ver** [sameersbn/docker-invoiceplane#26]
Hi,

I get always this error:

>  nginx: [emerg] host not found in upstream "invoiceplane" in /etc/nginx/sites-enabled/InvoicePlane.conf:30

This is my docker-compose.yml file:
```yaml
version: '2'

services:
  mysql:
    restart: always
    image: sameersbn/mysql:5.7.24
    environment:
    - DB_USER=invoiceplane
    - DB_PASS=nnHJaxpzcXehVKbfFcRk92twsHHxzm7w9T6TtZZTFw3EdbvDhSz
    - DB_NAME=invoiceplane_db
    volumes:
    - /srv/docker/invoiceplane/mysql:/var/lib/mysql

  invoiceplane:
    restart: always
    image: sameersbn/invoiceplane:1.5.9-2
    command: app:invoiceplane
    environment:
    - DEBUG=false
    - TZ=Europe/Berlin

    - DB_TYPE=mysqli
    - DB_HOST=mysql
    - DB_USER=invoiceplane
    - DB_PASS=nnHJaxpzcXehVKbfFcRk92twsHHxzm7w9T6TtZZTFw3EdbvDhSz
    - DB_NAME=invoiceplane_db

    - INVOICEPLANE_URL=http://localhost:10080
    - INVOICEPLANE_PROXY_IPS=
    - INVOICEPLANE_BACKUPS_EXPIRY=0
    depends_on:
    - mysql
    volumes:
    - /srv/docker/invoiceplane/invoiceplane:/var/lib/invoiceplane

  nginx:
    restart: always
    networks:
      - web
    container_name: buchhaltung
    image: sameersbn/invoiceplane:1.5.9-2
    command: app:nginx
    environment:
    - INVOICEPLANE_PHP_FPM_HOST=invoiceplane
    - INVOICEPLANE_PHP_FPM_PORT=9000
    depends_on:
    - invoiceplane
    ports:
    - "10080:10080"
    volumes_from:
    - invoiceplane
    labels:
      - "traefik.enable=true"
      - "traefik.backend=buchhaltung.kiefer-networks"
      - "traefik.frontend=buchhaltung.kiefer-networks"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:buchhaltung.kiefer-networks.de"
      - "traefik.port=10080"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
networks:
  web:
    external: true

```
